# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AgentLoop(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.BashTool", "types.GlobTool", "types.GrepTool", "types.LSTool", "types.ExitPlanModeTool", "types.ReadTool", "types.WebFetchTool", "types.TodoReadTool", "types.TodoWriteTool", "types.WebSearchTool", "types.EditTool", "types.MultiEditTool", "types.WriteTool", "types.NotebookEditTool", "types.PytestRunTool", "types.LintTool", "types.TypeCheckTool", "types.FormatTool", "types.DependencyTool", "types.GitDiffTool", "types.InstallPackagesTool", "types.ArtifactManagementTool", "types.AgentTool", "types.ReplyToUser"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AgentLoop", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.BashTool", "types.GlobTool", "types.GrepTool", "types.LSTool", "types.ExitPlanModeTool", "types.ReadTool", "types.WebFetchTool", "types.TodoReadTool", "types.TodoWriteTool", "types.WebSearchTool", "types.EditTool", "types.MultiEditTool", "types.WriteTool", "types.NotebookEditTool", "types.PytestRunTool", "types.LintTool", "types.TypeCheckTool", "types.FormatTool", "types.DependencyTool", "types.GitDiffTool", "types.InstallPackagesTool", "types.ArtifactManagementTool", "types.AgentTool", "types.ReplyToUser"], result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, result)

    def SubAgentLoop(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.BashTool", "types.GlobTool", "types.GrepTool", "types.LSTool", "types.ExitPlanModeTool", "types.ReadTool", "types.WebFetchTool", "types.TodoReadTool", "types.TodoWriteTool", "types.WebSearchTool", "types.EditTool", "types.MultiEditTool", "types.WriteTool", "types.NotebookEditTool", "types.PytestRunTool", "types.LintTool", "types.TypeCheckTool", "types.FormatTool", "types.DependencyTool", "types.GitDiffTool", "types.InstallPackagesTool", "types.ArtifactManagementTool", "types.ReplyToUser"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="SubAgentLoop", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.BashTool", "types.GlobTool", "types.GrepTool", "types.LSTool", "types.ExitPlanModeTool", "types.ReadTool", "types.WebFetchTool", "types.TodoReadTool", "types.TodoWriteTool", "types.WebSearchTool", "types.EditTool", "types.MultiEditTool", "types.WriteTool", "types.NotebookEditTool", "types.PytestRunTool", "types.LintTool", "types.TypeCheckTool", "types.FormatTool", "types.DependencyTool", "types.GitDiffTool", "types.InstallPackagesTool", "types.ArtifactManagementTool", "types.ReplyToUser"], result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AgentLoop(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.BashTool", "stream_types.GlobTool", "stream_types.GrepTool", "stream_types.LSTool", "stream_types.ExitPlanModeTool", "stream_types.ReadTool", "stream_types.WebFetchTool", "stream_types.TodoReadTool", "stream_types.TodoWriteTool", "stream_types.WebSearchTool", "stream_types.EditTool", "stream_types.MultiEditTool", "stream_types.WriteTool", "stream_types.NotebookEditTool", "stream_types.PytestRunTool", "stream_types.LintTool", "stream_types.TypeCheckTool", "stream_types.FormatTool", "stream_types.DependencyTool", "stream_types.GitDiffTool", "stream_types.InstallPackagesTool", "stream_types.ArtifactManagementTool", "stream_types.AgentTool", "stream_types.ReplyToUser"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="AgentLoop", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.BashTool", "stream_types.GlobTool", "stream_types.GrepTool", "stream_types.LSTool", "stream_types.ExitPlanModeTool", "stream_types.ReadTool", "stream_types.WebFetchTool", "stream_types.TodoReadTool", "stream_types.TodoWriteTool", "stream_types.WebSearchTool", "stream_types.EditTool", "stream_types.MultiEditTool", "stream_types.WriteTool", "stream_types.NotebookEditTool", "stream_types.PytestRunTool", "stream_types.LintTool", "stream_types.TypeCheckTool", "stream_types.FormatTool", "stream_types.DependencyTool", "stream_types.GitDiffTool", "stream_types.InstallPackagesTool", "stream_types.ArtifactManagementTool", "stream_types.AgentTool", "stream_types.ReplyToUser"], result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, result)

    def SubAgentLoop(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.BashTool", "stream_types.GlobTool", "stream_types.GrepTool", "stream_types.LSTool", "stream_types.ExitPlanModeTool", "stream_types.ReadTool", "stream_types.WebFetchTool", "stream_types.TodoReadTool", "stream_types.TodoWriteTool", "stream_types.WebSearchTool", "stream_types.EditTool", "stream_types.MultiEditTool", "stream_types.WriteTool", "stream_types.NotebookEditTool", "stream_types.PytestRunTool", "stream_types.LintTool", "stream_types.TypeCheckTool", "stream_types.FormatTool", "stream_types.DependencyTool", "stream_types.GitDiffTool", "stream_types.InstallPackagesTool", "stream_types.ArtifactManagementTool", "stream_types.ReplyToUser"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="SubAgentLoop", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.BashTool", "stream_types.GlobTool", "stream_types.GrepTool", "stream_types.LSTool", "stream_types.ExitPlanModeTool", "stream_types.ReadTool", "stream_types.WebFetchTool", "stream_types.TodoReadTool", "stream_types.TodoWriteTool", "stream_types.WebSearchTool", "stream_types.EditTool", "stream_types.MultiEditTool", "stream_types.WriteTool", "stream_types.NotebookEditTool", "stream_types.PytestRunTool", "stream_types.LintTool", "stream_types.TypeCheckTool", "stream_types.FormatTool", "stream_types.DependencyTool", "stream_types.GitDiffTool", "stream_types.InstallPackagesTool", "stream_types.ArtifactManagementTool", "stream_types.ReplyToUser"], result)

    