# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (29)
# #########################################################################

class AgentTool(BaseModel):
    action: typing.Optional[str] = None
    description: typing.Optional[str] = None
    prompt: typing.Optional[str] = None

class ArtifactManagementTool(BaseModel):
    action: typing.Optional[str] = None
    action_type: typing.Optional[str] = None
    folder: typing.Optional[str] = None
    pattern: typing.Optional[str] = None
    artifact_type: typing.Optional[str] = None

class BashTool(BaseModel):
    action: typing.Optional[str] = None
    command: typing.Optional[str] = None
    timeout: typing.Optional[int] = None
    description: typing.Optional[str] = None

class DependencyTool(BaseModel):
    action: typing.Optional[str] = None
    check_type: typing.Optional[str] = None
    requirements_file: typing.Optional[str] = None
    packages: typing.Optional[typing.List[str]] = None
    update_available: typing.Optional[bool] = None
    include_dev: typing.Optional[bool] = None

class EditOperation(BaseModel):
    old_string: typing.Optional[str] = None
    new_string: typing.Optional[str] = None
    replace_all: typing.Optional[bool] = None

class EditTool(BaseModel):
    action: typing.Optional[str] = None
    file_path: typing.Optional[str] = None
    old_string: typing.Optional[str] = None
    new_string: typing.Optional[str] = None
    replace_all: typing.Optional[bool] = None

class ExitPlanModeTool(BaseModel):
    action: typing.Optional[str] = None
    plan: typing.Optional[str] = None

class FormatTool(BaseModel):
    action: typing.Optional[str] = None
    target_path: typing.Optional[str] = None
    check_only: typing.Optional[bool] = None
    diff: typing.Optional[bool] = None
    line_length: typing.Optional[int] = None
    skip_string_normalization: typing.Optional[bool] = None
    target_version: typing.Optional[str] = None

class GitDiffTool(BaseModel):
    action: typing.Optional[str] = None
    target_path: typing.Optional[str] = None
    reference: typing.Optional[str] = None
    staged: typing.Optional[bool] = None
    stat: typing.Optional[bool] = None
    context_lines: typing.Optional[int] = None
    ignore_whitespace: typing.Optional[bool] = None

class GlobTool(BaseModel):
    action: typing.Optional[str] = None
    pattern: typing.Optional[str] = None
    path: typing.Optional[str] = None

class GrepTool(BaseModel):
    action: typing.Optional[str] = None
    pattern: typing.Optional[str] = None
    path: typing.Optional[str] = None
    include: typing.Optional[str] = None

class InstallPackagesTool(BaseModel):
    action: typing.Optional[str] = None
    packages: typing.List[str]
    dev: typing.Optional[bool] = None
    upgrade: typing.Optional[bool] = None
    user_confirmed: typing.Optional[bool] = None

class LSTool(BaseModel):
    action: typing.Optional[str] = None
    path: typing.Optional[str] = None
    ignore: typing.Optional[typing.List[str]] = None

class LintTool(BaseModel):
    action: typing.Optional[str] = None
    target_path: typing.Optional[str] = None
    fix: typing.Optional[bool] = None
    show_fixes: typing.Optional[bool] = None
    select_codes: typing.Optional[str] = None
    ignore: typing.Optional[str] = None
    format: typing.Optional[str] = None

class Message(BaseModel):
    role: typing.Optional[typing.Union[str, str]] = None
    message: typing.Optional[typing.Union[str, "BashTool", "GlobTool", "GrepTool", "LSTool", "ExitPlanModeTool", "ReadTool", "WebFetchTool", "TodoReadTool", "TodoWriteTool", "WebSearchTool", "EditTool", "MultiEditTool", "WriteTool", "NotebookEditTool", "PytestRunTool", "LintTool", "TypeCheckTool", "FormatTool", "DependencyTool", "GitDiffTool", "InstallPackagesTool", "ArtifactManagementTool", "AgentTool"]] = None

class MultiEditTool(BaseModel):
    action: typing.Optional[str] = None
    file_path: typing.Optional[str] = None
    edits: typing.List["EditOperation"]

class NotebookEditTool(BaseModel):
    action: typing.Optional[str] = None
    notebook_path: typing.Optional[str] = None
    cell_number: typing.Optional[int] = None
    new_source: typing.Optional[str] = None
    cell_type: typing.Optional[str] = None
    edit_mode: typing.Optional[str] = None

class NotebookReadTool(BaseModel):
    action: typing.Optional[str] = None
    notebook_path: typing.Optional[str] = None

class PytestRunTool(BaseModel):
    action: typing.Optional[str] = None
    test_path: typing.Optional[str] = None
    verbose: typing.Optional[bool] = None
    capture: typing.Optional[str] = None
    markers: typing.Optional[str] = None
    keywords: typing.Optional[str] = None
    max_failures: typing.Optional[int] = None
    timeout: typing.Optional[int] = None

class ReadTool(BaseModel):
    action: typing.Optional[str] = None
    file_path: typing.Optional[str] = None
    offset: typing.Optional[int] = None
    limit: typing.Optional[int] = None

class ReplyToUser(BaseModel):
    action: typing.Optional[str] = None
    message: typing.Optional[str] = None

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class TodoItem(BaseModel):
    content: typing.Optional[str] = None
    status: typing.Optional[typing.Union[str, str, str]] = None
    priority: typing.Optional[typing.Union[str, str, str]] = None
    id: typing.Optional[str] = None

class TodoReadTool(BaseModel):
    action: typing.Optional[str] = None

class TodoWriteTool(BaseModel):
    action: typing.Optional[str] = None
    todos: typing.List["TodoItem"]

class TypeCheckTool(BaseModel):
    action: typing.Optional[str] = None
    target_path: typing.Optional[str] = None
    checker: typing.Optional[str] = None
    strict: typing.Optional[bool] = None
    ignore_missing_imports: typing.Optional[bool] = None
    incremental: typing.Optional[bool] = None
    config_file: typing.Optional[str] = None

class WebFetchTool(BaseModel):
    action: typing.Optional[str] = None
    url: typing.Optional[str] = None
    prompt: typing.Optional[str] = None
    save_to_file: typing.Optional[str] = None

class WebSearchTool(BaseModel):
    action: typing.Optional[str] = None
    query: typing.Optional[str] = None
    allowed_domains: typing.Optional[typing.List[str]] = None
    blocked_domains: typing.Optional[typing.List[str]] = None

class WriteTool(BaseModel):
    action: typing.Optional[str] = None
    file_path: typing.Optional[str] = None
    content: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (4)
# #########################################################################


AgentTools: typing_extensions.TypeAlias = typing.Optional[typing.Union["BashTool", "GlobTool", "GrepTool", "LSTool", "ExitPlanModeTool", "ReadTool", "WebFetchTool", "TodoReadTool", "TodoWriteTool", "WebSearchTool", "EditTool", "MultiEditTool", "WriteTool", "NotebookEditTool", "PytestRunTool", "LintTool", "TypeCheckTool", "FormatTool", "DependencyTool", "GitDiffTool", "InstallPackagesTool", "ArtifactManagementTool", "AgentTool"]]


CodingTools: typing_extensions.TypeAlias = typing.Optional[typing.Union["PytestRunTool", "LintTool", "TypeCheckTool", "FormatTool", "DependencyTool", "GitDiffTool", "InstallPackagesTool", "ArtifactManagementTool"]]


ScaryTools: typing_extensions.TypeAlias = typing.Optional[typing.Union["EditTool", "MultiEditTool", "WriteTool", "NotebookEditTool", "TodoWriteTool"]]


SubAgentTools: typing_extensions.TypeAlias = typing.Optional[typing.Union["BashTool", "GlobTool", "GrepTool", "LSTool", "ExitPlanModeTool", "ReadTool", "WebFetchTool", "TodoReadTool", "TodoWriteTool", "WebSearchTool", "EditTool", "MultiEditTool", "WriteTool", "NotebookEditTool", "PytestRunTool", "LintTool", "TypeCheckTool", "FormatTool", "DependencyTool", "GitDiffTool", "InstallPackagesTool", "ArtifactManagementTool"]]
