# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AgentTool": types.AgentTool,
    "stream_types.AgentTool": stream_types.AgentTool,

    "types.ArtifactManagementTool": types.ArtifactManagementTool,
    "stream_types.ArtifactManagementTool": stream_types.ArtifactManagementTool,

    "types.BashTool": types.BashTool,
    "stream_types.BashTool": stream_types.BashTool,

    "types.DependencyTool": types.DependencyTool,
    "stream_types.DependencyTool": stream_types.DependencyTool,

    "types.EditOperation": types.EditOperation,
    "stream_types.EditOperation": stream_types.EditOperation,

    "types.EditTool": types.EditTool,
    "stream_types.EditTool": stream_types.EditTool,

    "types.ExitPlanModeTool": types.ExitPlanModeTool,
    "stream_types.ExitPlanModeTool": stream_types.ExitPlanModeTool,

    "types.FormatTool": types.FormatTool,
    "stream_types.FormatTool": stream_types.FormatTool,

    "types.GitDiffTool": types.GitDiffTool,
    "stream_types.GitDiffTool": stream_types.GitDiffTool,

    "types.GlobTool": types.GlobTool,
    "stream_types.GlobTool": stream_types.GlobTool,

    "types.GrepTool": types.GrepTool,
    "stream_types.GrepTool": stream_types.GrepTool,

    "types.InstallPackagesTool": types.InstallPackagesTool,
    "stream_types.InstallPackagesTool": stream_types.InstallPackagesTool,

    "types.IntentClassification": types.IntentClassification,
    "stream_types.IntentClassification": stream_types.IntentClassification,

    "types.LSTool": types.LSTool,
    "stream_types.LSTool": stream_types.LSTool,

    "types.LintTool": types.LintTool,
    "stream_types.LintTool": stream_types.LintTool,

    "types.Message": types.Message,
    "stream_types.Message": stream_types.Message,

    "types.MultiEditTool": types.MultiEditTool,
    "stream_types.MultiEditTool": stream_types.MultiEditTool,

    "types.NotebookEditTool": types.NotebookEditTool,
    "stream_types.NotebookEditTool": stream_types.NotebookEditTool,

    "types.NotebookReadTool": types.NotebookReadTool,
    "stream_types.NotebookReadTool": stream_types.NotebookReadTool,

    "types.PytestRunTool": types.PytestRunTool,
    "stream_types.PytestRunTool": stream_types.PytestRunTool,

    "types.ReadTool": types.ReadTool,
    "stream_types.ReadTool": stream_types.ReadTool,

    "types.ReplyToUser": types.ReplyToUser,
    "stream_types.ReplyToUser": stream_types.ReplyToUser,

    "types.ReplyWithCode": types.ReplyWithCode,
    "stream_types.ReplyWithCode": stream_types.ReplyWithCode,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.TodoItem": types.TodoItem,
    "stream_types.TodoItem": stream_types.TodoItem,

    "types.TodoReadTool": types.TodoReadTool,
    "stream_types.TodoReadTool": stream_types.TodoReadTool,

    "types.TodoWriteTool": types.TodoWriteTool,
    "stream_types.TodoWriteTool": stream_types.TodoWriteTool,

    "types.TypeCheckTool": types.TypeCheckTool,
    "stream_types.TypeCheckTool": stream_types.TypeCheckTool,

    "types.WebFetchTool": types.WebFetchTool,
    "stream_types.WebFetchTool": stream_types.WebFetchTool,

    "types.WebSearchTool": types.WebSearchTool,
    "stream_types.WebSearchTool": stream_types.WebSearchTool,

    "types.WriteTool": types.WriteTool,
    "stream_types.WriteTool": stream_types.WriteTool,


    "types.UserIntent": types.UserIntent,

}